#!/usr/bin/env python3

def is_level_data(line: str) -> bool:
    return not (':' in line or ';' in line or line.strip() == '')


with open("levels.txt", "r") as f:
    lines = f.read().splitlines()

print("; This file is automatically generated by level2asm.py")
print("; from levels.txt and data.nolevels.asm")
print("; Do not edit this file directly.\n")
with open("data.nolevels.asm", "r") as f:
    print(f.read())
print('SECTION "Levels", ROM0')

l = []
labels = []
for line in lines:
    if line.endswith(':'):
        labels.append(line[:-1])
        length = max((len(s) for s in l if is_level_data(s)), default=0)
        while l:
            print(f'  DB "{l.pop(0):<{length}}\\n"' if is_level_data(l[0]) else l.pop(0))
    l.append(line)

if len(l) > 0:
    length = max((len(s) for s in l if is_level_data(s)), default=0)
    while l:
        print(f'  DB "{l.pop(0):<{length}}\\n"' if is_level_data(l[0]) else l.pop(0))

print('LevelEnd:\n\nLevelTable:')
for label in labels:
    print(f'  DW {label}')