#!/usr/bin/env python3

def is_level_data(line: str) -> bool:
    return not (':' in line or ';' in line or line.strip() == '')


with open("levels.txt", "r") as f:
    lines = f.read().splitlines()

print("; This file is automatically generated by level2asm.py")
print("; from levels.txt and data.nolevels.asm")
print("; Do not edit this file directly.\n")
with open("data.nolevels.asm", "r") as f:
    print(f.read())
print('SECTION "Levels", ROM0')

l = []
labels = []
cnt = 0
max_line = 0
upper_space = 5
lower_space = 0
left_space = 0
right_space = 0
line_size = 20
flag = False
level = 1
man = []
boxes = []
this_level_box = 0
for line in lines: 
    if len(line) > 0 and line[0] == ';':
        print(line)
        continue
    elif line == "" and flag:
        print("Lv" + str(level) + ":")
        level += 1
        upper_space = 5 + (8 - cnt) // 2
        lower_space = 18 - upper_space - cnt
        print(f'  DB "                LV{(level-1):02d}"')
        print(f'  DB "                 000"')
        print('  DB "                    "\n' * (upper_space - 3) + '  DB "                    "')
        for label in labels:
            left_space = (line_size - len(label)) // 2
            right_space = line_size - left_space - len(label)
            print('  DB "' + ' ' * left_space + label + " " * right_space + '"')
        print('  DB "                    "\n' * lower_space)
        boxes.append(this_level_box)
        this_level_box = 0
        cnt = 0
        labels = []
    elif not line.endswith(":"):
        for x in range(len(line)):
            if line[x] == '.':
                this_level_box += 1
            elif line[x] == '@':
                x_pos = x + 1
                y_pos = cnt + 1
                man.append(dict(x=x_pos, y=y_pos))
        labels.append(line)
        max_line = max(max_line, len(line))
        cnt = cnt + 1
    if len(line) > 0:
        flag = True

# Print level 11
print("Lv" + str(level) + ":")
level += 1
upper_space = 5 + (8 - cnt) // 2
lower_space = 18 - upper_space - cnt
print(f'  DB "                LV{(level-1):02d}"')
print(f'  DB "                 000"')
print('  DB "                    "\n' * (upper_space - 3) + '  DB "                    "')
for label in labels:
    left_space = (line_size - len(label)) // 2
    right_space = line_size - left_space - len(label)
    print('  DB "' + ' ' * left_space + label + " " * right_space + '"')
print('  DB "                    "\n' * lower_space)
boxes.append(this_level_box)
this_level_box = 0
cnt = 0
labels = []

print('LevelEnd:\n\nLevelTable:')
for i in range(1, level):
    print(f'  DW Lv{i}')

print('\nLevelInfo:')
print("; record: x_pos, y_pos, box_num")
for i in range(0, level - 1):
    print(f'  DB {str(man[i]["x"])}, {str(man[i]["y"])}, {str(boxes[i])}')