.PHONY: run all clean rebuild debug

all: build/game.gb

data.asm: levels.txt data.nolevels.asm level2asm.py
	echo "; This file is automatically generated from levels.txt and data.nolevels.asm" > data.asm
	echo "; Do not edit this file directly." >> data.asm
	echo >> data.asm
	cat data.nolevels.asm >> data.asm
	echo >> data.asm
	python3 level2asm.py >> data.asm

debug: main.asm data.asm hardware.inc | build
	rgbasm -Weverything -E -o build/debug.o main.asm
	rgblink -n build/debug.sym -m build/debug.map -o build/debug.gb build/debug.o
	rgbfix -v -p 0xFF build/debug.gb
ifeq ($(OS),Windows_NT)
	cmd /c start build\debug.gb
else
	xdg-open build/debug.gb
endif

build:
	mkdir build

# assemble
build/main.o: main.asm data.asm hardware.inc | build
	rgbasm -o $@ $<

# link and fix
build/game.gb: build/main.o
	rgblink -o $@ $<
	rgbfix -v -p 0xFF $@

run: build/game.gb
ifeq ($(OS),Windows_NT)
	cmd /c start build\game.gb
else
	xdg-open build/game.gb
endif

clean:
ifeq ($(OS),Windows_NT)
	cmd /c if exist build rd /s /q build
else
	rm -rf build
endif

rebuild: clean all